// <auto-generated />
using E_Parcela.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Parcela.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230925094845_Final3")]
    partial class Final3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Parcela.Models.Parcele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParcelaCategory")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuradniciID")
                        .HasColumnType("int");

                    b.Property<int>("ZaposleniciID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuradniciID");

                    b.HasIndex("ZaposleniciID");

                    b.ToTable("Parcele");
                });

            modelBuilder.Entity("E_Parcela.Models.Sadnice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FUllName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sadnice");
                });

            modelBuilder.Entity("E_Parcela.Models.Sadnice_Parcele", b =>
                {
                    b.Property<int>("SadniceID")
                        .HasColumnType("int");

                    b.Property<int>("ParceleID")
                        .HasColumnType("int");

                    b.HasKey("SadniceID", "ParceleID");

                    b.HasIndex("ParceleID");

                    b.ToTable("Sadnice_Parcele");
                });

            modelBuilder.Entity("E_Parcela.Models.Suradnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suradnici");
                });

            modelBuilder.Entity("E_Parcela.Models.Zaposlenici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zaposlenici");
                });

            modelBuilder.Entity("E_Parcela.Models.Parcele", b =>
                {
                    b.HasOne("E_Parcela.Models.Suradnici", "Suradnici")
                        .WithMany("Parcele")
                        .HasForeignKey("SuradniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Parcela.Models.Zaposlenici", "Zaposlenici")
                        .WithMany("Parcele")
                        .HasForeignKey("ZaposleniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suradnici");

                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("E_Parcela.Models.Sadnice_Parcele", b =>
                {
                    b.HasOne("E_Parcela.Models.Parcele", "Parcele")
                        .WithMany("Sadnice_Parcele")
                        .HasForeignKey("ParceleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Parcela.Models.Sadnice", "Sadnice")
                        .WithMany("Sadnice_Parcele")
                        .HasForeignKey("SadniceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcele");

                    b.Navigation("Sadnice");
                });

            modelBuilder.Entity("E_Parcela.Models.Parcele", b =>
                {
                    b.Navigation("Sadnice_Parcele");
                });

            modelBuilder.Entity("E_Parcela.Models.Sadnice", b =>
                {
                    b.Navigation("Sadnice_Parcele");
                });

            modelBuilder.Entity("E_Parcela.Models.Suradnici", b =>
                {
                    b.Navigation("Parcele");
                });

            modelBuilder.Entity("E_Parcela.Models.Zaposlenici", b =>
                {
                    b.Navigation("Parcele");
                });
#pragma warning restore 612, 618
        }
    }
}
